Repository CAU-DM/DearMe_DEMO, pull requests merged in 2024-06, with the labels that each got.

#29 [DEV] Database Refactoring
  .gitignore
  backend/ai.py
  backend/db.py
  backend/requirements.txt
  backend/server.py
  backend/uploads/cheon.png
  frontend/src/App.js
  frontend/src/calendar/Cells.js
  frontend/src/chat/Chat.module.css
  frontend/src/chat/ChatWindow.js
  frontend/src/chat/PhotoDrop.js
  frontend/src/feed/FeedItem.js
  frontend/src/feed/FeedPage.js
  frontend/src/login/Login.js
  frontend/yarn.lock
Labels: DEV

#33 [DEV] Save Image button 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/src/feed/Feed.module.css
  frontend/src/feed/FeedItem.js
  frontend/src/feed/FeedPage.js
  frontend/yarn.lock
Labels: DEV

#35 [DEV] save diary 오류 수정
  frontend/src/feed/FeedItem.js
  frontend/src/feed/FeedPage.js
Labels: DEV

#36 [DEV, FIX] 일기 수정 기능 구현 및 캘린더 버그 수정
  .gitignore
  backend/ai.py
  backend/server.py
  frontend/src/calendar/Cells.js
  frontend/src/chat/ChatWindow.js
  frontend/src/chat/PhotoDrop.js
  frontend/src/feed/FeedItem.js
  frontend/src/feed/FeedPage.js
  frontend/src/login/Login.js
  frontend/yarn.lock
Labels: DEV, FIX

#38 [FIX] UI 개선작업 완료
  frontend/src/App.css
  frontend/src/Header.js
  frontend/src/chat/Chat.module.css
  frontend/src/chat/ChatWindow.js
  frontend/src/chat/PhotoDrop.js
  frontend/src/feed/Feed.module.css
  frontend/src/feed/FeedItem.js
Labels: FIX

#40 [DEV, FIX] UI개선, 입력창 자동 줄 높이 기능 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/chat/Chat.module.css
  frontend/src/chat/ChatWindow.js
  frontend/src/feed/Feed.module.css
  frontend/src/feed/FeedItem.js
  frontend/yarn.lock
Labels: DEV, FIX

#42 [DEV] 최종 배포를 위한 준비
  backend/ai.py
  backend/moderation.py
  backend/moderation_test.ipynb
  backend/requirements.txt
  backend/server.py
  embedding.ipynb
  frontend/src/chat/Chat.module.css
  frontend/src/chat/ChatWindow.js
  initialize.sh
Labels: DEV
