Repository CAU-DM/DearMe_DEMO, pull requests merged in 2024-05, with the labels that each got.

#1 [DEV] react, ai, flask 대통합 성공
  README.md
  backend/ai.py
  backend/newFlaskTest.py
  backend/server.py
  backend/templates/index.html
  frontend/package.json
  frontend/src/App.js
  frontend/src/ChatWindow.js
Labels: DEV

#4 [DEV] UI 리디자인 작업 및 로그인 페이지 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/logo512_nb.png
  frontend/public/logo_text.png
  frontend/public/logo_text_c.png
  frontend/public/reset.css
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/ChatWindow.js
  frontend/src/GoogleLoginButton.js
  frontend/src/Header.js
  frontend/yarn.lock
Labels: DEV

#6 [DEV] Google OAuth 구현
  README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/GoogleLoginButton.js
  frontend/src/index.js
  frontend/src/login/Login.js
  frontend/src/login/Login.module.css
  frontend/src/login/firebase-config.js
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
  frontend/yarn.lock
  initialize.sh
  start_server.sh
Labels: DEV

#9 [DEV] Demo 전까지 구현 (FrontEnd)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/FeedItem.js
  frontend/src/Header.js
  frontend/src/chat/Chat.module.css
  frontend/src/chat/ChatWindow.js
  frontend/src/chat/PhotoDrop.js
  frontend/src/feed/Feed.module.css
  frontend/src/feed/FeedItem.js
  frontend/src/feed/FeedPage.js
  frontend/src/login/Login.js
  frontend/src/login/Login.module.css
  frontend/yarn.lock
  package-lock.json
  package.json
Labels: DEV

#10 [DEV] backend demo 구현
  .gitignore
  backend/ai.py
  backend/db.py
  backend/requirements.txt
  backend/server.py
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/Header.js
  frontend/src/chat/Chat.module.css
  frontend/src/chat/ChatWindow.js
  frontend/src/feed/FeedPage.js
  frontend/src/login/Login.js
  prompt.txt
Labels: DEV

#19 [DEV] Generate 버튼 리디자인
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/chat/Chat.module.css
  frontend/src/chat/ChatWindow.js
  package-lock.json
  package.json
Labels: DEV

#21 [DEV, FIX] 팀 소개 페이지 추가, UI 개선 작업
  frontend/package-lock.json
  frontend/package.json
  frontend/public/img/empty_0.png
  frontend/public/img/empty_1.png
  frontend/public/img/empty_2.png
  frontend/public/img/empty_3.png
  frontend/public/img/team_illust.png
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/Header.js
  frontend/src/chat/Chat.module.css
  frontend/src/chat/ChatWindow.js
  frontend/src/feed/Feed.module.css
  frontend/src/feed/FeedItem.js
  frontend/src/feed/FeedPage.js
  frontend/src/login/Login.module.css
  frontend/yarn.lock
Labels: DEV, FIX

#23 [DEV] Calendar Merge
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/Header.js
  frontend/src/calendar/CalendarButton.js
  frontend/src/calendar/CalendarPage.js
  frontend/src/calendar/Cells.js
  frontend/src/calendar/Days.js
  frontend/src/calendar/FeedButton.js
  frontend/src/calendar/Months.js
  frontend/src/chat/Chat.module.css
  frontend/src/feed/FeedItem.js
  frontend/src/feed/FeedPage.js
  frontend/src/login/Login.js
  frontend/src/tailwind.css
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: DEV

#25 [DEV] 캘린더 날짜 배경화면 추가
  frontend/src/calendar/Cells.js
Labels: DEV

#26 [FIX] Header 반응형 UI 관련 작업 및 PhotoDrop UI 변경
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/Header.js
  frontend/src/chat/ChatWindow.js
  frontend/src/chat/PhotoDrop.js
  frontend/yarn.lock
  package-lock.json
  package.json
Labels: FIX
